version: '3.6'
volumes:
  knit_mysql_data: {}
networks:
  main: {}
services:
  nginx:
    build:
      context: nginx
      args:
        - KNIT_API_TAG=latest
        - KNIT_API_ADMIN_TAG=latest
        - KNIT_HOMEPAGE_TAG=latest
        - ADMIN_PUBLIC_URL=/admin
        - 'ADMIN_API_URL=http://api.knit.pk.edu.pl'
    depends_on:
      - api
    environment:
      - PORT=9988
      - 'API_URL=http://api:9501'
    networks:
      main:
        aliases:
          - static.proxy
    ports:
      - '8100:9988'
    volumes:
      - './volumes/images:/usr/src/api/public/media/upload:ro'
  varnish:
    build:
      context: varnish
    restart: always
    networks:
      main:
        aliases:
          - api.knit.pk.edu.pl
    depends_on:
      - api
      - nginx
    ports:
      - '80:80'
  api:
    image: 'knitpk/api:latest'
    restart: always
    environment:
      - HOST=api
    networks:
      - main
    volumes:
      - './volumes/images:/usr/src/api/public/media/upload:rw'
  homepage:
    image: 'knitpk/homepage:latest'
    restart: always
    networks:
      - main
  redis:
    build:
      context: redis
    restart: always
    networks:
      - main
  mysql:
    image: 'mysql:5.7'
    restart: always
    networks:
      - main
    volumes:
      - 'knit_mysql_data:/var/lib/mysql'
  pma:
    build:
      context: pma
    restart: always
    networks:
      - main
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
    ports:
      - '8000:80'
