version: '3.6'
volumes:
  knit_mysql_data: {}

networks:
  main:
    name: knit_main
  homepage:
    name: knit_homepage

services:
  reverse-proxy:
    restart: always
    image: traefik:latest
    networks: 
      - main
    ports:
      - "80:80"
    volumes:
      - './volumes/acme:/etc/traefik/acme'
      - /var/run/docker.sock:/var/run/docker.sock

  static-proxy:
    image: 'knitpk/static-proxy:latest'
    restart: always
    networks: 
      - main
    build:
      context: static-proxy
      args:
        - KNIT_API_TAG=latest
        - KNIT_API_ADMIN_TAG=latest
        - KNIT_HOMEPAGE_TAG=latest
        - ADMIN_PUBLIC_URL=/admin
        - 'ADMIN_API_URL=http://api.knit.pk.edu.pl'
    depends_on:
      - api
    environment:
      - PORT=9988
      - 'API_URL=http://api:9501'
      - 'HOMEPAGE_URL=http://homepage:3000'
    volumes:
      - './volumes/images:/usr/src/api/public/media/upload:ro'
    labels:
      traefik.enable: true
      traefik.port: 9988
      traefik.frontend.rule: Host:api.knit.pk.edu.pl,www.knit.pk.edu.pl,knit.pk.edu.pl

  caching-proxy:
    image: 'knitpk/caching-proxy:latest'
    restart: always
    networks: 
      main: {}
      homepage:
        aliases: 
          - api.knit.pk.edu.pl
    build:
      context: caching-proxy
    depends_on:
      - api
      - static-proxy
    labels:
      traefik.docker.network: knit_main
      traefik.enable: true
      traefik.port: 80
      traefik.frontend.rule: Host:api.knit.pk.edu.pl

  api:
    image: 'knitpk/api:latest'
    restart: always
    networks: 
      - main
    environment:
      - HOST=api
    volumes:
      - './volumes/images:/usr/src/api/public/media/upload:rw'

  homepage:
    image: 'knitpk/homepage:latest'
    restart: always
    networks: 
      - main
      - homepage
    environment:
      - PORT=3000
      - NODE_ENV=production
      - 'API_URL=http://api.knit.pk.edu.pl'
    labels:
      traefik.docker.network: knit_main
      traefik.enable: true
      traefik.port: 3000
      traefik.frontend.rule: Host:knit.pk.edu.pl

  redis:
    image: 'knitpk/redis:latest'
    restart: always
    networks: 
      - main
    build:
      context: redis

  mysql:
    image: 'mysql:5.7'
    restart: always
    networks: 
      - main
    volumes:
      - 'knit_mysql_data:/var/lib/mysql'
      
  pma:
    image: 'knitpk/pma:latest'
    restart: always
    networks: 
      - main
    build:
      context: pma
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
