version: '3.6'
services:
  api:
    env_file: .env.api
      
  redis:
    environment:
      - REDIS_PASSWORD=Passw0rd
  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=Passw0rd
  pma:
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=Passw0rd
