version: "3"

volumes:
  mysql_data:

services:

  nginx:
    build:
      context: nginx
      args: 
        - KNIT_API_TAG=0.7.0-dev
        - KNIT_HOMEPAGE_TAG=0.1.5-dev
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./volumes/images:/usr/src/api/public/media/upload


  varnish:
    build:
      context: varnish
    restart: always
    depends_on:
      - nginx
    ports:
      - "80:80"

  api:
    image: knitpk/api:0.7.0-dev
    restart: always
    volumes:
      - ./volumes/images:/usr/src/api/public/media/upload

  homepage:
    image: knitpk/homepage:0.1.5-dev
    restart: always
    
  redis:
    build:
      context: redis
    restart: always

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql

  pma:
    build:
      context: pma
    restart: always
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
    ports:
      - "8000:80"