version: "3"

volumes:
  mysql_data:

networks: 
  main:

services:
  nginx:
    build:
      context: nginx
      args: 
        - KNIT_API_TAG=0.7.0-dev
        - KNIT_API_ADMIN_TAG=0.3.1-dev
        - KNIT_HOMEPAGE_TAG=0.1.5-dev
    restart: always
    networks: 
      - main
    ports:
      - "8080:80"
    volumes:
      - ./volumes/images:/usr/src/api/public/media/upload


  varnish:
    build:
      context: varnish
    restart: always
    networks: 
      main:
        aliases:
          - api.knit.pk.edu.pl
    depends_on:
      - nginx
    ports:
      - "80:80"

  api:
    image: knitpk/api:0.7.0-dev
    restart: always
    networks: 
      - main
    volumes:
      - ./volumes/images:/usr/src/api/public/media/upload

  homepage:
    image: knitpk/homepage:0.1.5-dev
    restart: always
    networks: 
      - main
    
  redis:
    build:
      context: redis
    restart: always
    networks: 
      - main

  mysql:
    image: mysql:5.7
    restart: always
    networks: 
      - main
    volumes:
      - mysql_data:/var/lib/mysql

  pma:
    build:
      context: pma
    restart: always
    networks: 
      - main
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
    ports:
      - "8000:80"